### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by impactrudia** [pro00er/projobsearcher_scraping_learning#4]
## 마감기한  
- 2018년 7월 20일

## scrapy 학습
- scrapy  :python crawler 책 예제로 변형해보기 - 페어프로그래밍  
  - Scrapy tutorial 실습 - 리스트 뿌려주기  
## python 학습 
- 책 코딩트레이닝(브라이언호건 저)에서 3개 문제 골라서 해보기
  - python 참조 자료 보면서 해보기
  -  [X] 연습문제2. 글자 수 세기
  -  연습문제 27. 입력 값 검증
     - [ ] @ohahohah
     - [X] @RudiaMoon       
  - [ ] 연습문제 42. 데이터 파일 파싱

## 정규식(개인학습)
- [ ] @ohahohah - hackerrank Regex 풀기 
- [ ] RudiaMoon - 프로그래머스 정규식 강의실습

## 온라인 작업 환경설정
- [ ] c9 세팅
