### ISSUE TITLE
log_180707_실습방안

### ISSUE THREAD

**Issue by impactrudia** [pro00er/projobsearcher_scraping_learning#9]
**Body**
- 부평역_스타벅스_파이썬 학습중

**TODO**
- 온라인으로 페어 진행
 - TDD와 Pair진행.
 - 연습문제 42
- 파이썬 전체 진도 확인
-  회고 30분

**CheckList**
- [X] issue title 형식 지킴? (exercise_8자리날짜_간략주제 , e.g. exercise_20180628_코딩트레이닝_연습문제26)
- [X] assignees , labels 확인하기 
- [X] issue body는 issue body만 확인하고도 모르는 사람도 내용을 파악할 수 있을 정도로 적었는가? (무엇을,언제,어디서)
